### PR TITLE
Chapter 2.6 Exercise

### LINKED ISSUE #127: Exercise 20: Relational and Logical Operators in C ("relational_logical_operators") ("Chapter 2.6")
Looking for help creating exercise:
Topic: **Relational and Logical Operators in C**
Exercise Directory Name: **relational_logical_operators**

Note: For Directory Name, refer to the exercises directory to find the correct number to use. It should be close to the number in the issue title but may be slightly off.

Refer to "The C Programming Language" book, Chapter 2.6 for more information.

Contribution instructions: https://github.com/danwritecode/clings?tab=readme-ov-file#contributions

### PR DESCRIPTION
**Pull request by sleaper**
Resolves #127

### CODE REVIEW

**Comment by danwritecode** [comment]
Some feedback on the exercise and high level feedback: 

1. I want to try to not directly or closely replicate what the book is doing. I think we should conceptually use the book as a rough guide but create or own unique exercises. 
2. This particular exercise has a LOT of context to take in, it took me a while to figure out what I was looking at and what I should even do. We want to make sure our users are not confused when they open a new exercise. 

I will update the contribution guide to better explain the first point so that future contributors have a clearer picture on expectations. 

Do you mind taking another swing at this with your own example? I think we should probably have two exercises here, one for relational operators and one for logical operators, and we should leverage assert to create compile time errors. For the logical operators we can come up with something that is tricky for the user by utilizing && and ||.

**Comment by danwritecode** [comment]
Check out what I did in this PR, my goal was to create some sort of "gotcha" that makes the user think about what the problem is while also teaching them the concept of thing they are looking to learn

https://github.com/danwritecode/clings/pull/168

**Comment by sleaper** [comment]
Yes, you're right. I didn't realize the book is still being sold in stores, so I can't use the exact exercises from it. That would violate copyright law. We should be cautious about this. I'll take another swing at it with my own examples.
Thanks for the feedback!

**Review by danwritecode — APPROVED** [review]
This is great!

**Pull request merged**
